name: labeler

on: push

permissions: write-all

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: 🏷️ Labeler
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: false
          dry-run: false
          exclude: |
            help*
            *issue
